import { NextRequest, NextResponse } from "next/server";

// POST /api/send-email - Send PDF link via email (optional)
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { email, pdfUrl, fileName } = body;

    if (!email || !pdfUrl) {
      return NextResponse.json(
        { success: false, error: "email and pdfUrl are required" },
        { status: 400 }
      );
    }

    const resendApiKey = process.env.RESEND_API_KEY;
    const fromEmail = process.env.FROM_EMAIL || "noreply@texttopdf.app";

    if (!resendApiKey) {
      console.log(
        `[Email] Skipped (no RESEND_API_KEY). Would send to: ${email}, PDF: ${pdfUrl}`
      );
      return NextResponse.json({
        success: false,
        skipped: true,
        message: "Email service not configured. Set RESEND_API_KEY to enable.",
      });
    }

    const response = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${resendApiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        from: `Text to PDF <${fromEmail}>`,
        to: [email],
        subject: "Your PDF is Ready",
        html: `
          <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
            <div style="background: linear-gradient(135deg, #2563eb, #1d4ed8); padding: 30px; border-radius: 12px 12px 0 0; text-align: center;">
              <h1 style="color: white; margin: 0; font-size: 24px;">Your PDF is Ready</h1>
            </div>
            <div style="background: white; padding: 30px; border: 1px solid #e5e7eb; border-top: none; border-radius: 0 0 12px 12px;">
              <p style="color: #374151; font-size: 16px; line-height: 1.6;">Hello,</p>
              <p style="color: #374151; font-size: 16px; line-height: 1.6;">Your PDF <strong>${fileName || "document.pdf"}</strong> has been generated successfully.</p>
              <a href="${pdfUrl}" style="display: inline-block; background: #2563eb; color: white; padding: 12px 24px; border-radius: 8px; text-decoration: none; font-size: 16px; margin: 16px 0;">Download PDF</a>
              <p style="color: #6b7280; font-size: 14px; margin-top: 20px;">Generated by Text to PDF Converter</p>
            </div>
          </div>
        `,
      }),
    });

    if (!response.ok) {
      const errorText = await response.text();
      console.error("Resend API error:", response.status, errorText);
      return NextResponse.json(
        { success: false, error: "Failed to send email" },
        { status: 502 }
      );
    }

    const data = await response.json();
    return NextResponse.json({
      success: true,
      messageId: data.id,
      message: `Email sent to ${email}`,
    });
  } catch (error) {
    console.error("Email send error:", error);
    return NextResponse.json(
      { success: false, error: "Failed to send email" },
      { status: 500 }
    );
  }
}
